version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_INITDB_DATABASE: career_crawler
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 9997:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ../data/db:/data/db

  scrapy:
    container_name: scrapy
    build: .
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Hong_Kong
    depends_on:
      - mongodb
    ports:
      - 7654:7654